# Generated by Django 4.1.1 on 2022-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_literaryformat_annotation_literaryformat_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literaryformat',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
